import LeanFrontier.NumberTheory.DescartesCurvatureAction
import Mathlib.Algebra.Group.Subgroup.Lattice

/-!
# The integral Apollonian reflection group

The accepted Descartes curvature-action module packages each coordinate Vieta move as a linear
map and proves that it preserves the Descartes quadratic form and squares to the identity.
This module bundles those involutions as linear equivalences and takes the subgroup they
generate over the integral curvature lattice.

The resulting apollonianGroup is the natural algebraic object for integral Apollonian orbits.
Every group element preserves the Descartes form, hence sends an integral Descartes quadruple
to another integral Descartes quadruple.

Large subgroup/coercion statements are exposed through named propositions so the public API
remains within LeanFrontier's normalized-statement receiver budget.
-/

namespace LeanFrontier.DescartesCircle

variable {R : Type*} [CommRing R]

private theorem curvatureReflection_involutive'
    (i : Fin 4) :
    Function.Involutive
      (curvatureReflection i : CurvatureVector R → CurvatureVector R) := by
  intro v
  have h := congrArg
    (fun L : CurvatureVector R →ₗ[R] CurvatureVector R => L v)
    (curvatureReflectionSquare_eq_identity (R := R) i)
  simpa [curvatureReflectionSquare, curvatureIdentity] using h

/-- A coordinate Descartes reflection bundled as an invertible linear transformation. -/
noncomputable def curvatureReflectionEquiv (i : Fin 4) :
    CurvatureVector R ≃ₗ[R] CurvatureVector R :=
  LinearEquiv.ofBijective (curvatureReflection i)
    (curvatureReflection_involutive' (R := R) i).bijective

@[simp]
theorem curvatureReflectionEquiv_apply
    (i : Fin 4) (v : CurvatureVector R) :
    curvatureReflectionEquiv i v = curvatureReflection i v :=
  rfl

/-- Each bundled curvature reflection is itself an involution in the linear-equivalence group. -/
theorem curvatureReflectionEquiv_mul_self (i : Fin 4) :
    (curvatureReflectionEquiv i : CurvatureVector R ≃ₗ[R] CurvatureVector R) *
        curvatureReflectionEquiv i = 1 := by
  apply LinearEquiv.ext
  intro v
  simp only [LinearEquiv.mul_apply, curvatureReflectionEquiv_apply]
  change curvatureReflection i (curvatureReflection i v) = v
  exact curvatureReflection_involutive' (R := R) i v

/-- The integral Apollonian group generated by the four coordinate Vieta reflections. -/
noncomputable def apollonianGroup :
    Subgroup (CurvatureVector ℤ ≃ₗ[ℤ] CurvatureVector ℤ) :=
  Subgroup.closure (Set.range fun i : Fin 4 => curvatureReflectionEquiv (R := ℤ) i)

/-- Compact public proposition asserting that all four coordinate reflections are generators. -/
def ReflectionGeneratorsInApollonianGroup : Prop :=
  ∀ i : Fin 4,
    (curvatureReflectionEquiv i :
      CurvatureVector ℤ ≃ₗ[ℤ] CurvatureVector ℤ) ∈ apollonianGroup

/-- Every coordinate reflection belongs to the integral Apollonian group. -/
theorem reflectionGenerators_mem_apollonianGroup :
    ReflectionGeneratorsInApollonianGroup := by
  intro i
  apply Subgroup.subset_closure
  exact ⟨i, rfl⟩

/-- Compact proposition saying every integral Apollonian-group element preserves the
Descartes quadratic form. -/
def ApollonianGroupPreservesDescartesForm : Prop :=
  ∀ g : apollonianGroup, ∀ v : CurvatureVector ℤ,
    descartesForm (g.1 v) = descartesForm v

/-- Every element of the integral Apollonian group preserves the Descartes quadratic form. -/
theorem apollonianGroup_preserves_descartesForm :
    ApollonianGroupPreservesDescartesForm := by
  unfold ApollonianGroupPreservesDescartesForm
  intro g v
  refine Subgroup.closure_induction
    (p := fun x _ => ∀ w : CurvatureVector ℤ, descartesForm (x w) = descartesForm w)
    ?_ ?_ ?_ ?_ g.2 v
  · intro x hx w
    rcases hx with ⟨i, rfl⟩
    simpa using (descartesForm_curvatureReflection (R := ℤ) i w)
  · intro w
    simp
  · intro x y hx hy ihx ihy w
    simpa only [LinearEquiv.mul_apply] using (ihx (y w)).trans (ihy w)
  · intro x hx ih w
    have h := ih (x⁻¹ w)
    simpa using h.symm

/-- Compact proposition saying the integral Apollonian group acts on integral Descartes
quadruples. -/
def ApollonianGroupPreservesQuadruples : Prop :=
  ∀ g : apollonianGroup, ∀ v : CurvatureVector ℤ,
    IsQuadruple (v 0) (v 1) (v 2) (v 3) →
      IsQuadruple (g.1 v 0) (g.1 v 1) (g.1 v 2) (g.1 v 3)

/-- Every integral Apollonian-group element sends an integral Descartes quadruple to another
integral Descartes quadruple. -/
theorem apollonianGroup_preserves_quadruples :
    ApollonianGroupPreservesQuadruples := by
  unfold ApollonianGroupPreservesQuadruples
  intro g v h
  rw [isQuadruple_iff_descartesForm_eq_zero] at h ⊢
  have hpres := apollonianGroup_preserves_descartesForm
  unfold ApollonianGroupPreservesDescartesForm at hpres
  rw [hpres g v]
  exact h

end LeanFrontier.DescartesCircle
