import LeanFrontier.NumberTheory.DescartesCurvatureAction
import Mathlib.Algebra.Group.Subgroup.Lattice

/-!
# The integral Apollonian reflection group

The accepted Descartes curvature-action module packages each coordinate Vieta move as a linear
map and proves that it preserves the Descartes quadratic form and squares to the identity.
This module bundles those involutions as linear equivalences and takes the subgroup they
generate over the integral curvature lattice.

The resulting `apollonianGroup` is the natural algebraic object for integral Apollonian
orbits. Every group element preserves the Descartes form, hence sends an integral Descartes
quadruple to another integral Descartes quadruple.
-/

namespace LeanFrontier.DescartesCircle

variable {R : Type*} [CommRing R]

private theorem curvatureReflection_involutive'
    (i : Fin 4) :
    Function.Involutive
      (curvatureReflection i : CurvatureVector R → CurvatureVector R) := by
  intro v
  have h := congrArg
    (fun L : CurvatureVector R →ₗ[R] CurvatureVector R => L v)
    (curvatureReflectionSquare_eq_identity (R := R) i)
  simpa [curvatureReflectionSquare, curvatureIdentity] using h

/-- A coordinate Descartes reflection bundled as an invertible linear transformation. -/
noncomputable def curvatureReflectionEquiv (i : Fin 4) :
    CurvatureVector R ≃ₗ[R] CurvatureVector R :=
  LinearEquiv.ofBijective (curvatureReflection i)
    (curvatureReflection_involutive' (R := R) i).bijective

@[simp]
theorem curvatureReflectionEquiv_apply
    (i : Fin 4) (v : CurvatureVector R) :
    curvatureReflectionEquiv i v = curvatureReflection i v :=
  rfl

/-- Each bundled curvature reflection is itself an involution in the linear-equivalence group. -/
theorem curvatureReflectionEquiv_mul_self (i : Fin 4) :
    (curvatureReflectionEquiv i : CurvatureVector R ≃ₗ[R] CurvatureVector R) *
        curvatureReflectionEquiv i = 1 := by
  ext v
  simp only [LinearEquiv.mul_apply, curvatureReflectionEquiv_apply]
  exact curvatureReflection_involutive' (R := R) i v

/-- The integral Apollonian group generated by the four coordinate Vieta reflections. -/
noncomputable def apollonianGroup :
    Subgroup (CurvatureVector ℤ ≃ₗ[ℤ] CurvatureVector ℤ) :=
  Subgroup.closure (Set.range fun i : Fin 4 => curvatureReflectionEquiv (R := ℤ) i)

/-- Every coordinate reflection is one of the generators of the integral Apollonian group. -/
theorem curvatureReflectionEquiv_mem_apollonianGroup (i : Fin 4) :
    (curvatureReflectionEquiv i :
      CurvatureVector ℤ ≃ₗ[ℤ] CurvatureVector ℤ) ∈ apollonianGroup := by
  apply Subgroup.subset_closure
  exact ⟨i, rfl⟩

/-- Every element of the integral Apollonian group preserves the Descartes quadratic form. -/
theorem descartesForm_apollonianGroup
    (g : apollonianGroup) (v : CurvatureVector ℤ) :
    descartesForm (g.1 v) = descartesForm v := by
  induction g.2 using Subgroup.closure_induction generalizing v with
  | mem x hx =>
      rcases hx with ⟨i, rfl⟩
      simpa using (descartesForm_curvatureReflection (R := ℤ) i v)
  | one =>
      simp
  | mul x y hx hy ihx ihy =>
      simpa only [LinearEquiv.mul_apply] using (ihx (y v)).trans (ihy v)
  | inv x hx ih =>
      have h := ih (x⁻¹ v)
      simpa using h.symm

/-- The integral Apollonian group acts on integral Descartes quadruples: every group element
takes a curvature vector satisfying the Descartes equation to another one satisfying it. -/
theorem isQuadruple_apollonianGroup
    (g : apollonianGroup) (v : CurvatureVector ℤ)
    (h : IsQuadruple (v 0) (v 1) (v 2) (v 3)) :
    IsQuadruple
      (g.1 v 0) (g.1 v 1) (g.1 v 2) (g.1 v 3) := by
  rw [isQuadruple_iff_descartesForm_eq_zero] at h ⊢
  rw [descartesForm_apollonianGroup]
  exact h

end LeanFrontier.DescartesCircle
