import LeanFrontier.NumberTheory.DescartesCurvatureAction
import Mathlib.Algebra.Group.Subgroup.Lattice

/-!
# The integral Apollonian reflection group

The accepted Descartes curvature-action module packages each coordinate Vieta move as a linear
map and proves that it preserves the Descartes quadratic form and squares to the identity.
This module bundles those involutions as linear equivalences and takes the subgroup they
generate over the integral curvature lattice.

The resulting `apollonianGroup` is the natural algebraic object for integral Apollonian orbits.
Its public certificate states that every group element sends an integral Descartes quadruple to
another integral Descartes quadruple.
-/

namespace LeanFrontier.DescartesCircle

variable {R : Type*} [CommRing R]

private theorem curvatureReflection_involutive'
    (i : Fin 4) :
    Function.Involutive
      (curvatureReflection i : CurvatureVector R → CurvatureVector R) := by
  intro v
  have h := congrArg
    (fun L : CurvatureVector R →ₗ[R] CurvatureVector R => L v)
    (curvatureReflectionSquare_eq_identity (R := R) i)
  simpa [curvatureReflectionSquare, curvatureIdentity] using h

/-- A coordinate Descartes reflection bundled as an invertible linear transformation. -/
noncomputable def curvatureReflectionEquiv (i : Fin 4) :
    CurvatureVector R ≃ₗ[R] CurvatureVector R :=
  LinearEquiv.ofBijective (curvatureReflection i)
    (curvatureReflection_involutive' (R := R) i).bijective

@[simp]
private theorem curvatureReflectionEquiv_apply
    (i : Fin 4) (v : CurvatureVector R) :
    curvatureReflectionEquiv i v = curvatureReflection i v :=
  rfl

/-- The integral Apollonian group generated by the four coordinate Vieta reflections. -/
noncomputable def apollonianGroup :
    Subgroup (CurvatureVector ℤ ≃ₗ[ℤ] CurvatureVector ℤ) :=
  Subgroup.closure (Set.range fun i : Fin 4 => curvatureReflectionEquiv (R := ℤ) i)

/-- A compact proof certificate that the integral Apollonian group acts on integral
Descartes quadruples. Packaging the quantified action as a structure keeps the public theorem
small while retaining the full mathematical content. -/
structure ApollonianGroupActionCertificate : Prop where
  preserves :
    ∀ g : apollonianGroup, ∀ v : CurvatureVector ℤ,
      IsQuadruple (v 0) (v 1) (v 2) (v 3) →
        IsQuadruple (g.1 v 0) (g.1 v 1) (g.1 v 2) (g.1 v 3)

/-- The integral Apollonian group preserves integral Descartes quadruples. -/
theorem apollonianGroup_action_certificate :
    ApollonianGroupActionCertificate := by
  constructor
  intro g v h
  rw [isQuadruple_iff_descartesForm_eq_zero] at h ⊢
  have hpres : descartesForm (g.1 v) = descartesForm v := by
    refine Subgroup.closure_induction
      (p := fun x _ => ∀ w : CurvatureVector ℤ, descartesForm (x w) = descartesForm w)
      ?_ ?_ ?_ ?_ g.2 v
    · intro x hx w
      rcases hx with ⟨i, rfl⟩
      simpa [curvatureReflectionEquiv_apply] using
        (descartesForm_curvatureReflection (R := ℤ) i w)
    · intro w
      simp
    · intro x y hx hy ihx ihy w
      simpa only [LinearEquiv.mul_apply] using (ihx (y w)).trans (ihy w)
    · intro x hx ih w
      have hinv := ih (x⁻¹ w)
      simpa using hinv.symm
  rw [hpres]
  exact h

end LeanFrontier.DescartesCircle
