#!/usr/bin/env python3
"""Research-only Markov/Farey experiments for LeanFrontier.

This file is deliberately not a Lean submission. It mirrors the accepted
OrientedNode/child recursion closely enough to test proposed bridges before
formalization.

Experiments:
1. verify-orientation: verify a six-state transducer carrying the planar
   Farey/Markov left-centre-right frame into LeanFrontier's coordinate-labelled
   oriented tree.
2. search-collisions: enumerate the planar Markov tree below a numerical bound
   and look for duplicate maximal Markov labels attached to distinct unordered
   triples.
3. recognize-root: construct Zhang's matrix from a modular root and test
   membership in the positive Cohn monoid generated by A and B.
4. scan-palindromes: enumerate matrices M_(a p b) with p palindromic, record
   collisions of their candidate denominators, and distinguish central
   palindromes (the Christoffel/Markov subclass) from arbitrary palindromes.

The searches are exploratory sanity checks. Finite negative searches are not
evidence for the open uniqueness conjecture.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from enum import IntEnum
from itertools import product
from math import gcd, isqrt


class Move(IntEnum):
    FIRST = 0
    SECOND = 1
    THIRD = 2


State = tuple[int, int, int]


@dataclass(frozen=True)
class Oriented:
    state: State
    back: Move


def jump(b: int, c: int, a: int) -> int:
    return 3 * b * c - a


def move(which: Move, state: State) -> State:
    x, y, z = state
    if which == Move.FIRST:
        return (jump(y, z, x), y, z)
    if which == Move.SECOND:
        return (x, jump(x, z, y), z)
    return (x, y, jump(x, y, z))


def forward_move(back: Move, direction: bool) -> Move:
    table = {
        Move.FIRST: (Move.SECOND, Move.THIRD),
        Move.SECOND: (Move.FIRST, Move.THIRD),
        Move.THIRD: (Move.FIRST, Move.SECOND),
    }
    return table[back][1 if direction else 0]


def child(node: Oriented, direction: bool) -> Oriented:
    changed = forward_move(node.back, direction)
    return Oriented(move(changed, node.state), changed)


ORIENTED_ROOT = Oriented((1, 1, 2), Move.THIRD)


def follow(bits: tuple[bool, ...]) -> Oriented:
    node = ORIENTED_ROOT
    for bit in bits:
        node = child(node, bit)
    return node


# A frame stores which physical coordinate currently means
# (left Farey boundary, centre/Markov number, right Farey boundary).
Frame = tuple[Move, Move, Move]

# At (1, 2, 1), put the left boundary in coordinate SECOND, the centre in
# coordinate THIRD, and the right boundary in coordinate FIRST. With this
# convention the first classical L/R step maps to Lean false/true.
ROOT_FRAME: Frame = (Move.SECOND, Move.THIRD, Move.FIRST)


def direction_for_changed_coordinate(back: Move, target: Move) -> bool:
    for direction in (False, True):
        if forward_move(back, direction) == target:
            return direction
    raise AssertionError("target must be one of the two non-back coordinates")


def frame_step(frame: Frame, planar_direction: str) -> tuple[bool, Frame]:
    left, centre, right = frame
    if planar_direction == "L":
        out = direction_for_changed_coordinate(centre, right)
        return out, (left, right, centre)
    if planar_direction == "R":
        out = direction_for_changed_coordinate(centre, left)
        return out, (centre, left, right)
    raise ValueError("planar path must contain only L/R")


def translate_planar_path(path: str) -> tuple[tuple[bool, ...], Frame]:
    frame = ROOT_FRAME
    bits: list[bool] = []
    for step in path:
        out, frame = frame_step(frame, step)
        bits.append(out)
    return tuple(bits), frame


@dataclass(frozen=True)
class PlanarNode:
    """Planar Farey/Markov frame (left label, centre label, right label)."""

    left: int
    centre: int
    right: int


PLANAR_ROOT = PlanarNode(1, 2, 1)


def planar_child(node: PlanarNode, direction: str) -> PlanarNode:
    l, m, r = node.left, node.centre, node.right
    if direction == "L":
        return PlanarNode(l, 3 * l * m - r, m)
    if direction == "R":
        return PlanarNode(m, 3 * m * r - l, r)
    raise ValueError("planar path must contain only L/R")


def planar_follow(path: str) -> PlanarNode:
    node = PLANAR_ROOT
    for step in path:
        node = planar_child(node, step)
    return node


def expected_lean_state(planar: PlanarNode, frame: Frame) -> State:
    values = {
        frame[0]: planar.left,
        frame[1]: planar.centre,
        frame[2]: planar.right,
    }
    return (values[Move.FIRST], values[Move.SECOND], values[Move.THIRD])


def all_paths(max_depth: int):
    yield ""
    for depth in range(1, max_depth + 1):
        for letters in product("LR", repeat=depth):
            yield "".join(letters)


def verify_orientation(max_depth: int) -> None:
    checked = 0
    for path in all_paths(max_depth):
        bits, frame = translate_planar_path(path)
        lean = follow(bits)
        planar = planar_follow(path)
        expected = expected_lean_state(planar, frame)
        if lean.state != expected or lean.back != frame[1]:
            raise AssertionError(
                f"orientation mismatch at {path!r}: "
                f"lean={lean}, planar={planar}, frame={frame}, expected={expected}"
            )
        checked += 1

    print(f"verified {checked} planar nodes through depth {max_depth}")
    print("six-state transition table (frame=L/M/R coordinate numbers):")
    reachable = set()
    frontier = [ROOT_FRAME]
    while frontier:
        frame = frontier.pop()
        if frame in reachable:
            continue
        reachable.add(frame)
        for step in "LR":
            _, nxt = frame_step(frame, step)
            frontier.append(nxt)

    def frame_name(frame: Frame) -> str:
        return "".join(str(int(x) + 1) for x in frame)

    for frame in sorted(reachable, key=lambda f: tuple(map(int, f))):
        pieces = []
        for step in "LR":
            bit, nxt = frame_step(frame, step)
            pieces.append(f"{step}->{int(bit)}:{frame_name(nxt)}")
        print(f"  {frame_name(frame)}  " + "  ".join(pieces))

    print("sample planar path -> direct Lean child bits -> sternNode path")
    for path in ("L", "R", "LL", "LR", "RL", "RR", "LLL", "LLR"):
        bits, _ = translate_planar_path(path)
        direct = "".join("R" if b else "L" for b in bits)
        stern = direct[::-1]  # sternNode follows path.reverse
        print(f"  {path:3} -> {direct:3} -> {stern:3}")


def search_collisions(max_label: int) -> None:
    stack: list[tuple[str, PlanarNode]] = [("", PLANAR_ROOT)]
    by_label: dict[int, tuple[str, tuple[int, int, int]]] = {}
    collisions: list[
        tuple[int, tuple[str, tuple[int, int, int]], tuple[str, tuple[int, int, int]]]
    ] = []
    visited = 0
    deepest = 0

    while stack:
        path, node = stack.pop()
        if node.centre > max_label:
            continue
        visited += 1
        deepest = max(deepest, len(path))
        triple = tuple(sorted((node.left, node.centre, node.right)))
        old = by_label.get(node.centre)
        if old is not None and old[1] != triple:
            collisions.append((node.centre, old, (path, triple)))
        else:
            by_label[node.centre] = (path, triple)

        left = planar_child(node, "L")
        right = planar_child(node, "R")
        if left.centre <= max_label:
            stack.append((path + "L", left))
        if right.centre <= max_label:
            stack.append((path + "R", right))

    print(
        f"visited={visited} max_label={max_label} deepest_path={deepest} "
        f"distinct_labels={len(by_label)} collisions={len(collisions)}"
    )
    for item in collisions[:20]:
        print("collision:", item)




# Cohn generators used in the word model of Markov numbers.
# See Lagisquet--Pelantová--Tavenas--Vuillon (2021).
Matrix = tuple[tuple[int, int], tuple[int, int]]
A: Matrix = ((1, 1), (1, 2))
B: Matrix = ((2, 1), (1, 1))
A_INV: Matrix = ((2, -1), (-1, 1))
B_INV: Matrix = ((1, -1), (-1, 2))
IDENTITY: Matrix = ((1, 0), (0, 1))

# Ordinary positive SL_2(Z) Euclidean generators.  The Cohn generators
# factor as A = R*L and B = L*R.
L: Matrix = ((1, 1), (0, 1))
R: Matrix = ((1, 0), (1, 1))
L_INV: Matrix = ((1, -1), (0, 1))
R_INV: Matrix = ((1, 0), (-1, 1))


def matrix_mul(x: Matrix, y: Matrix) -> Matrix:
    return (
        (
            x[0][0] * y[0][0] + x[0][1] * y[1][0],
            x[0][0] * y[0][1] + x[0][1] * y[1][1],
        ),
        (
            x[1][0] * y[0][0] + x[1][1] * y[1][0],
            x[1][0] * y[0][1] + x[1][1] * y[1][1],
        ),
    )


def matrix_transpose(x: Matrix) -> Matrix:
    return ((x[0][0], x[1][0]), (x[0][1], x[1][1]))


def word_matrix(word: str) -> Matrix:
    out = IDENTITY
    for letter in word:
        if letter == "a":
            out = matrix_mul(out, A)
        elif letter == "b":
            out = matrix_mul(out, B)
        else:
            raise ValueError("Cohn words contain only a/b")
    return out


def root_core_matrix(modulus: int, root: int) -> Matrix:
    """Symmetric determinant-one core attached to a modular root.

    Put v=(u^2+1)/M. Then
      P(M,u) = [[M-2u+v, u-v], [u-v, v]]
    has determinant one, and A * P(M,u) * B is exactly the transposed
    Zhang candidate matrix used below.
    """
    if modulus <= 0:
        raise ValueError("modulus must be positive")
    root %= modulus
    if (root * root + 1) % modulus:
        raise ValueError("root must satisfy root^2 == -1 mod modulus")
    v = (root * root + 1) // modulus
    core = (
        (modulus - 2 * root + v, root - v),
        (root - v, v),
    )
    if core[0][0] * core[1][1] - core[0][1] * core[1][0] != 1:
        raise AssertionError("root core must have determinant one")
    return core


def zhang_candidate_matrix(modulus: int, root: int) -> Matrix:
    """Transpose of Zhang's Proposition-8 matrix, in our A/B convention."""
    core = root_core_matrix(modulus, root)
    candidate = matrix_mul(matrix_mul(A, core), B)

    root %= modulus
    v = (root * root + 1) // modulus
    expected = (
        (2 * modulus - root, modulus),
        (2 * modulus + root - v, modulus + root),
    )
    if candidate != expected:
        raise AssertionError("A * root_core * B must equal Zhang candidate")
    return candidate


def matrix_nonnegative(x: Matrix) -> bool:
    return all(entry >= 0 for row in x for entry in row)


def recognize_lr_word(x: Matrix) -> str | None:
    """Unique positive Euclidean word in L,R, when x lies in that monoid.

    Right stripping is deterministic for determinant-one nonnegative matrices:
    multiplying by L^-1 or R^-1 must keep all entries nonnegative.  For the
    positive symmetric root cores considered here this reaches the identity.
    """
    current = x
    reversed_word: list[str] = []
    for _ in range(100000):
        if current == IDENTITY:
            return "".join(reversed(reversed_word))
        choices: list[tuple[str, Matrix]] = []
        for letter, inverse in (("L", L_INV), ("R", R_INV)):
            parent = matrix_mul(current, inverse)
            if matrix_nonnegative(parent):
                choices.append((letter, parent))
        if len(choices) != 1:
            return None
        letter, current = choices[0]
        reversed_word.append(letter)
    raise RuntimeError("Euclidean word recognition did not terminate")


def lr_word_to_cohn_word(word: str) -> str | None:
    """Decode an L/R word in the fixed two-letter phase A=RL, B=LR."""
    if len(word) % 2:
        return None
    letters: list[str] = []
    for index in range(0, len(word), 2):
        pair = word[index:index + 2]
        if pair == "RL":
            letters.append("a")
        elif pair == "LR":
            letters.append("b")
        else:
            return None
    return "".join(letters)


def recognize_cohn_word(x: Matrix) -> str | None:
    """Recognize x in the free positive monoid generated by A and B.

    We strip a possible last generator by right multiplication by A^-1/B^-1.
    The DFS is tiny for the matrices considered here and also doubles as a
    check that no greedy convention has been smuggled into the experiment.
    """
    stack: list[tuple[Matrix, str]] = [(x, "")]
    seen: set[Matrix] = set()
    while stack:
        current, reversed_word = stack.pop()
        if current == IDENTITY:
            return reversed_word[::-1]
        if current in seen:
            continue
        seen.add(current)
        for letter, inverse in (("a", A_INV), ("b", B_INV)):
            parent = matrix_mul(current, inverse)
            if matrix_nonnegative(parent):
                stack.append((parent, reversed_word + letter))
    return None


def centered_index_from_word_matrix(x: Matrix) -> tuple[int, int]:
    """Return (candidate denominator, root modulo sign) for a special word."""
    modulus = x[0][1]
    if modulus <= 0:
        raise ValueError("expected positive upper-right entry")
    root = (x[1][1] - modulus) % modulus
    return modulus, min(root, modulus - root)


def is_period(word: str, period: int) -> bool:
    if period <= 0:
        return False
    if period >= len(word):
        return True
    return all(word[i] == word[i + period] for i in range(len(word) - period))


def is_central_palindrome(word: str) -> bool:
    """Classical central-word criterion: coprime periods p,q, |w|=p+q-2."""
    if word != word[::-1]:
        return False
    n = len(word)
    for p in range(1, n + 2):
        q = n + 2 - p
        if gcd(p, q) == 1 and is_period(word, p) and is_period(word, q):
            return True
    return False


def palindromes(length: int):
    half = (length + 1) // 2
    for bits in product("ab", repeat=half):
        first = "".join(bits)
        if length % 2 == 0:
            yield first + first[::-1]
        else:
            yield first + first[-2::-1]


def continued_fraction(numerator: int, denominator: int) -> list[int]:
    """Regular continued fraction of a positive rational numerator/denominator."""
    if numerator <= 0 or denominator <= 0:
        raise ValueError("continued fractions here expect positive arguments")
    out: list[int] = []
    while denominator:
        quotient, remainder = divmod(numerator, denominator)
        out.append(quotient)
        numerator, denominator = denominator, remainder
    return out


def continued_fraction_has_cohn_phase(digits: list[int]) -> bool:
    """Exact phase condition predicted by the L/R pairing A=RL, B=LR.

    For a centered modular-root core, the Euclidean L/R run lengths are the
    continued-fraction digits of M/u, except that the first and last runs are
    one shorter.  Pairability into RL/LR therefore becomes:
      * first and last continued-fraction digits are 2;
      * every digit is 1 or 2;
      * every maximal block of 1s has even length.
    """
    if not digits or digits[0] != 2 or digits[-1] != 2:
        return False
    if any(digit not in (1, 2) for digit in digits):
        return False
    index = 0
    while index < len(digits):
        if digits[index] != 1:
            index += 1
            continue
        end = index
        while end < len(digits) and digits[end] == 1:
            end += 1
        if (end - index) % 2:
            return False
        index = end
    return True


def root_to_sum_squares(modulus: int, root: int) -> tuple[int, int] | None:
    """Cornacchia descent attached to a square root of -1 modulo M.

    The centered root chooses one primitive Gaussian factor of M.  Euclidean
    descent from (M,u) stops at a <= sqrt(M); if M-a^2 is a square, the
    resulting pair (a,b) satisfies M=a^2+b^2.  For every root tested here the
    descent succeeds, as expected for roots of -1.
    """
    if modulus <= 0:
        raise ValueError("modulus must be positive")
    root %= modulus
    centered = min(root, (-root) % modulus)
    if centered == 0 or (centered * centered + 1) % modulus:
        return None

    r0, r1 = modulus, centered
    while r1 * r1 > modulus:
        r0, r1 = r1, r0 % r1

    a = r1
    b_squared = modulus - a * a
    if b_squared < 0:
        return None
    b = isqrt(b_squared)
    if b * b != b_squared:
        return None
    pair = tuple(sorted((a, b)))
    if gcd(pair[0], pair[1]) != 1:
        raise AssertionError("root of -1 should yield a primitive sum-of-two-squares pair")
    return pair


def verify_root_bridges(max_modulus: int) -> None:
    """Adversarial finite check of the exact root/matrix/CF/Gaussian bridges."""
    roots = 0
    cohn_roots = 0
    for modulus in range(3, max_modulus + 1):
        for root in range(1, modulus // 2 + 1):
            if (root * root + 1) % modulus:
                continue
            roots += 1
            core = root_core_matrix(modulus, root)
            lr_word = recognize_lr_word(core)
            if lr_word is None:
                raise AssertionError(f"missing L/R word for M={modulus}, u={root}")
            paired = lr_word_to_cohn_word(lr_word)
            phase = continued_fraction_has_cohn_phase(
                continued_fraction(modulus, root)
            )
            if (paired is not None) != phase:
                raise AssertionError(
                    f"CF/Cohn phase mismatch for M={modulus}, u={root}: "
                    f"cf={continued_fraction(modulus, root)} lr={lr_word} "
                    f"paired={paired}"
                )
            if paired is not None:
                cohn_roots += 1

            squares = root_to_sum_squares(modulus, root)
            if squares is None or squares[0] ** 2 + squares[1] ** 2 != modulus:
                raise AssertionError(
                    f"Cornacchia bridge failed for M={modulus}, u={root}"
                )

    print(
        f"verified root bridges for M<= {max_modulus}: "
        f"centered_roots={roots} cohn_phase_roots={cohn_roots}"
    )


def centered_mod_root(value: int, modulus: int) -> int:
    if modulus <= 1:
        return 0
    residue = value % modulus
    return min(residue, (-residue) % modulus)


def arithmetic_cohn_descent(modulus: int, root: int):
    """Arithmetic form of palindromic Cohn-core descent.

    The input root is centered to 0 < u <= M/2.  For
      v = (u^2 + 1) / M,
    the centered symmetric modular-root core is
      [[M-2u+v, u-v], [u-v, v]].

    If it is a nontrivial B-wrapped Cohn palindrome, stripping the outer B
    gives a parent whose m-value is exactly v.  The one scalar
      h = -M + 5u - 6v
    is the off-diagonal entry of that parent.

    We stop at the two smallest centered palindromic cores:
      (M,u)=(2,1): identity core, inner counts (0,0);
      (M,u)=(5,2): B core, inner counts (0,1).

    Returns a dictionary suitable for exploratory printing.
    """
    u = centered_mod_root(root, modulus)
    if modulus == 2 and u == 1:
        return {"accepted": True, "steps": [], "inner_counts": (0, 0)}
    if modulus == 5 and u == 2:
        return {"accepted": True, "steps": [], "inner_counts": (0, 1)}

    steps = []
    M = modulus
    while (M, u) not in ((2, 1), (5, 2)):
        if M <= 1 or u <= 0 or 2 * u > M or (u * u + 1) % M:
            return {"accepted": False, "steps": steps, "reason": "not a centered root"}

        v = (u * u + 1) // M
        h = -M + 5 * u - 6 * v

        # Entries of Q = B^-1 P(M,u) B^-1.
        q11 = M - 4 * u + 4 * v
        q12 = h
        q22 = M - 6 * u + 9 * v

        if h < 0:
            return {
                "accepted": False,
                "steps": steps,
                "reason": "outer-B strip leaves the nonnegative cone",
                "failed_at": (M, u, v, h),
            }

        if min(q11, q12, q22) < 0:
            raise AssertionError(
                "h >= 0 should force the whole symmetric determinant-one parent nonnegative"
            )

        # The parent root represented by Q is q12+q22 = 3v-u (mod v).
        # Recenter it; exchanging A<->B corresponds to swapping Q's diagonal.
        parent_root_raw = q12 + q22
        parent_u = centered_mod_root(parent_root_raw, v)
        swap = 2 * parent_root_raw > v
        # Equivalent exact sign test: Q is already centered iff q11 >= q22,
        # i.e. iff 2u >= 5v.
        if swap != (2 * u < 5 * v):
            raise AssertionError("orientation tests disagree")

        steps.append(
            {
                "M": M,
                "u": u,
                "v": v,
                "h": h,
                "parent_matrix": ((q11, q12), (q12, q22)),
                "swap_parent": swap,
                "parent_u": parent_u,
            }
        )
        M, u = v, parent_u

    counts = (0, 0) if (M, u) == (2, 1) else (0, 1)
    a_count, b_count = counts
    for step in reversed(steps):
        if step["swap_parent"]:
            a_count, b_count = b_count, a_count + 2
        else:
            a_count, b_count = a_count, b_count + 2

    return {
        "accepted": True,
        "steps": steps,
        "inner_counts": (a_count, b_count),
        "whole_counts": (a_count + 1, b_count + 1),
    }



def verify_arithmetic_descent_normal_form(max_modulus: int) -> None:
    """Verify the exact quotient-2 normal form for centered modular roots.

    For v=(u^2+1)/M and h=-M+5u-6v, one has the identity
        v*h = (u-2v)*(3v-u) - 1.
    Hence h>=0 is equivalent (away from the explicitly accepted tiny bases)
    to the Euclidean quotient condition 2v < u < 3v.

    Writing r=u-2v then gives
        w=(r^2+1)/v,
        M=4v+4r+w,
        h=r-w,
    and the stripped symmetric core is
        [[w, r-w], [r-w, v-2r+w]].
    """
    checked = 0
    successful = 0
    for M in range(2, max_modulus + 1):
        for u in range(1, M // 2 + 1):
            if (u * u + 1) % M:
                continue
            checked += 1
            v = (u * u + 1) // M
            h = -M + 5 * u - 6 * v
            if v * h != (u - 2 * v) * (3 * v - u) - 1:
                raise AssertionError(("vh identity", M, u, v, h))

            quotient_two = 2 * v < u < 3 * v
            if (M, u) not in ((2, 1), (5, 2)) and (h >= 0) != quotient_two:
                raise AssertionError(("cone/quotient mismatch", M, u, v, h))

            if not quotient_two:
                continue
            successful += 1
            r = u - 2 * v
            if not (0 < r < v):
                raise AssertionError(("bad remainder range", M, u, v, r))
            if (r * r + 1) % v:
                raise AssertionError(("remainder lost sqrt(-1)", M, u, v, r))
            w = (r * r + 1) // v
            if M != 4 * v + 4 * r + w:
                raise AssertionError(("M normal form", M, u, v, r, w))
            if h != r - w:
                raise AssertionError(("h normal form", M, u, v, r, w, h))

            q = (
                (M - 4 * u + 4 * v, h),
                (h, M - 6 * u + 9 * v),
            )
            expected = ((w, r - w), (r - w, v - 2 * r + w))
            if q != expected:
                raise AssertionError(("parent matrix normal form", M, u, q, expected))

            parent_u = min(r, v - r)
            if parent_u <= 0 or (parent_u * parent_u + 1) % v:
                raise AssertionError(("bad centered parent root", M, u, v, r, parent_u))

    print(
        f"verified arithmetic descent normal form for M<= {max_modulus}: "
        f"centered_roots={checked} quotient_two_steps={successful}"
    )



def scan_markov_fake_roots(max_label: int) -> None:
    """Scan genuine Markov labels for non-genuine modular roots.

    Research-only optional dependency: SymPy is imported only by this command
    to factor the modulus and enumerate square roots of -1.

    For every distinct unordered positive Markov triple below max_label,
    compare the coordinate-defined genuine centered root with every other
    centered square root of -1 modulo the maximal coordinate.  Record how many
    quotient-two strips each fake root survives.
    """
    try:
        import sympy as sp
    except ImportError as exc:
        raise SystemExit(
            "scan-markov-fakes requires the optional research dependency sympy"
        ) from exc

    def genuine_root(node: PlanarNode) -> int:
        M = node.centre
        left = node.left % M
        right = node.right % M
        value = (left * pow(right, -1, M)) % M
        return min(value, (-value) % M)

    def survival_depth(M: int, root: int) -> tuple[int, bool, list[tuple[int,int,int]]]:
        u = centered_mod_root(root, M)
        depth = 0
        chain: list[tuple[int,int,int]] = []
        while True:
            if (M, u) in ((2, 1), (5, 2)):
                return depth, True, chain
            if M <= 1 or u <= 0 or 2 * u > M or (u * u + 1) % M:
                return depth, False, chain
            v = (u * u + 1) // M
            chain.append((M, u, v))
            if not (2 * v < u < 3 * v):
                return depth, False, chain
            r = u - 2 * v
            M, u = v, min(r, v - r)
            depth += 1

    stack: list[tuple[str, PlanarNode]] = [("", PLANAR_ROOT)]
    seen_triples: set[tuple[int,int,int]] = set()
    fake_count = 0
    full_survivors: list[tuple[int,int,int,str]] = []
    depth_histogram: dict[int,int] = {}
    longest: tuple[int,int,int,str,list[tuple[int,int,int]]] | None = None

    while stack:
        path, node = stack.pop()
        if node.centre > max_label:
            continue

        triple = tuple(sorted((node.left, node.centre, node.right)))
        if triple not in seen_triples:
            seen_triples.add(triple)
            M = node.centre
            if M > 2:
                genuine = genuine_root(node)
                all_roots = sp.sqrt_mod(-1, M, all_roots=True)
                centered = sorted(
                    {
                        min(int(root), M - int(root))
                        for root in all_roots
                        if int(root) not in (0, M)
                    }
                )
                for root in centered:
                    if root == genuine:
                        continue
                    fake_count += 1
                    depth, accepted, chain = survival_depth(M, root)
                    depth_histogram[depth] = depth_histogram.get(depth, 0) + 1
                    if accepted:
                        full_survivors.append((M, genuine, root, path))
                    if longest is None or depth > longest[0]:
                        longest = (depth, M, root, path, chain)

        for direction in "LR":
            child_node = planar_child(node, direction)
            if child_node.centre <= max_label:
                stack.append((path + direction, child_node))

    print(
        f"Markov fake-root scan M<= {max_label}: "
        f"distinct_triples={len(seen_triples)} fake_roots={fake_count} "
        f"full_survivors={len(full_survivors)}"
    )
    print("survival-depth histogram:", dict(sorted(depth_histogram.items())))
    if longest is not None:
        depth, M, root, path, chain = longest
        print(
            f"longest fake survivor: depth={depth} M={M} root={root} "
            f"path={path} chain={chain}"
        )
    if full_survivors:
        print("WARNING: fully Cohn-admissible non-genuine roots found:")
        for item in full_survivors[:20]:
            print(" ", item)

def compare_root_pair(modulus: int, root1: int, root2: int) -> None:
    """Inspect the exact pair dynamics for two centered roots of -1 mod M."""
    M = modulus
    u1 = centered_mod_root(root1, M)
    u2 = centered_mod_root(root2, M)
    if not (0 < u1 < u2 <= M // 2):
        if u1 == u2:
            raise ValueError("roots have the same centered representative")
        u1, u2 = sorted((u1, u2))
    for u in (u1, u2):
        if (u * u + 1) % M:
            raise ValueError(f"{u} is not a root of -1 modulo {M}")

    v1 = (u1 * u1 + 1) // M
    v2 = (u2 * u2 + 1) // M
    d = u2 - u1
    s = u1 + u2
    delta = v2 - v1
    if delta * M != d * s:
        raise AssertionError("pair factorization failed")

    r1 = u1 - 2 * v1
    r2 = u2 - 2 * v2

    from math import gcd
    split_d = gcd(M, d)
    split_s = M // split_d
    print(f"M={M} roots=({u1},{u2})")
    print(
        f"  d=u2-u1={d} s=u1+u2={s} "
        f"v=({v1},{v2}) delta={delta}"
    )
    print(
        f"  exact: delta*M=d*s -> {delta}*{M}={d}*{s}; "
        f"delta/d={delta/d:.12f}"
    )
    print(
        f"  CRT split proxy: gcd(M,d)={split_d}, complementary={split_s}, "
        f"d/s quotients=({d//split_d if split_d else 0},"
        f"{s//split_s if split_s and s % split_s == 0 else 'nonintegral'})"
    )
    print(
        f"  raw quotient-two remainders r=({r1},{r2}); "
        f"r1-r2={r1-r2}=2*delta-d={2*delta-d}"
    )

    admissible1 = 2 * v1 < u1 < 3 * v1
    admissible2 = 2 * v2 < u2 < 3 * v2
    print(f"  quotient-two admissible=({admissible1},{admissible2})")
    if admissible1 and admissible2:
        if not (2 * d < 3 * delta and delta < d):
            raise AssertionError("expected two-thirds contraction bound")
        print("  proven interval consequence: 2d/3 < delta < d")
        print("  therefore raw remainders strictly reverse order: r1 > r2")

    for label, u in (("root1", u1), ("root2", u2)):
        result = arithmetic_cohn_descent(M, u)
        print(
            f"  {label} descent accepted={result['accepted']} "
            f"counts={result.get('whole_counts')} "
            f"steps={[(x['M'], x['u'], x['v']) for x in result['steps']]}"
        )

def recognize_root(modulus: int, root: int) -> None:
    centered = min(root % modulus, (-root) % modulus)
    cf = continued_fraction(modulus, centered)
    first_bad = next((i for i, digit in enumerate(cf) if digit not in (1, 2)), None)
    print(f"M={modulus} centered_root={centered}")
    squares = root_to_sum_squares(modulus, centered)
    print(
        f"  M/u continued fraction={cf} all_1_or_2={first_bad is None} "
        f"cohn_cf_phase={continued_fraction_has_cohn_phase(cf)} "
        f"first_non_12_index={first_bad} sum_squares={squares}"
    )
    for representative in sorted({centered, (-centered) % modulus}):
        if (representative * representative + 1) % modulus:
            print(f"  {representative}: not a square root of -1")
            continue
        core = root_core_matrix(modulus, representative)
        candidate = zhang_candidate_matrix(modulus, representative)
        lr_word = recognize_lr_word(core)
        paired_word = None if lr_word is None else lr_word_to_cohn_word(lr_word)
        core_word = recognize_cohn_word(core)
        word = recognize_cohn_word(candidate)
        if word is None:
            print(
                f"  {representative}: candidate does not lie in <A,B>; "
                f"core={core} lr_word={lr_word} paired_word={paired_word} "
                f"core_word={core_word}"
            )
            continue
        inner = word[1:-1] if len(word) >= 2 and word[0] == "a" and word[-1] == "b" else None
        central = inner is not None and is_central_palindrome(inner)
        print(
            f"  {representative}: core={core} lr_word={lr_word} "
            f"paired_word={paired_word} core_word={core_word} "
            f"word={word} palindrome_inner="
            f"{inner is not None and inner == inner[::-1]} central={central}"
        )


def scan_palindromes(max_inner_length: int) -> None:
    """Search the wider a-palindrome-b class for denominator/root collisions."""
    # denominator -> centered root -> (one witness, central?, unordered endpoint counts)
    groups: dict[int, dict[int, tuple[str, bool, tuple[int, int]]]] = {}
    # A second index deliberately ignores the root and asks the stronger question:
    # can one m-value occur for two different unordered endpoint-count pairs?
    endpoint_groups: dict[int, dict[tuple[int, int], str]] = {}
    total_words = 0
    central_words = 0

    for inner_length in range(max_inner_length + 1):
        for inner in palindromes(inner_length):
            word = "a" + inner + "b"
            matrix = word_matrix(word)
            modulus, root = centered_index_from_word_matrix(matrix)

            # For a palindrome this identity follows symbolically from
            # A [[x,y],[y,z]] B; keep it as an executable guard.
            trace = matrix[0][0] + matrix[1][1]
            if trace != 3 * modulus:
                raise AssertionError(f"palindrome identity failed for {word}")

            central = is_central_palindrome(inner)
            counts = tuple(sorted((word.count("a"), word.count("b"))))
            total_words += 1
            central_words += int(central)
            roots = groups.setdefault(modulus, {})
            old = roots.get(root)
            if old is None or (central and not old[1]):
                roots[root] = (word, central, counts)
            endpoint_groups.setdefault(modulus, {}).setdefault(counts, word)

    broad_collisions = [
        (modulus, roots) for modulus, roots in groups.items() if len(roots) > 1
    ]
    mixed_collisions = [
        (modulus, roots)
        for modulus, roots in broad_collisions
        if any(central for _, central, _ in roots.values())
    ]
    cross_endpoint_collisions = [
        (modulus, endpoints)
        for modulus, endpoints in endpoint_groups.items()
        if len(endpoints) > 1
    ]

    print(
        f"inner<= {max_inner_length}: words={total_words} "
        f"candidate_denominators={len(groups)} central_words={central_words} "
        f"multi_root_denominators={len(broad_collisions)} "
        f"central_involved_multi_root={len(mixed_collisions)} "
        f"cross_endpoint_denominators={len(cross_endpoint_collisions)}"
    )

    print("first broad collisions:")
    for modulus, roots in sorted(broad_collisions)[:10]:
        summary = ", ".join(
            f"root={root} word={word} central={central} counts={counts}"
            for root, (word, central, counts) in sorted(roots.items())
        )
        print(f"  M={modulus}: {summary}")

    if mixed_collisions:
        print("WARNING: central-involved collisions found")
        for modulus, roots in sorted(mixed_collisions)[:20]:
            print(f"  M={modulus}: {roots}")
    else:
        print("no central-involved collision in this finite scan")

    if cross_endpoint_collisions:
        print("WARNING: equal m-values across distinct endpoint-count pairs found")
        for modulus, endpoints in sorted(cross_endpoint_collisions)[:20]:
            print(f"  M={modulus}: {endpoints}")
    else:
        print("no equal m-value across distinct unordered endpoint counts in this finite scan")


def main() -> None:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)

    verify = sub.add_parser("verify-orientation")
    verify.add_argument("--depth", type=int, default=12)

    search = sub.add_parser("search-collisions")
    search.add_argument(
        "--digits",
        type=int,
        default=100,
        help="search nodes with centre Markov label <= 10**digits",
    )

    root = sub.add_parser("recognize-root")
    root.add_argument("modulus", type=int)
    root.add_argument("root", type=int)

    pal = sub.add_parser("scan-palindromes")
    pal.add_argument("--inner", type=int, default=30)

    descent = sub.add_parser("descent-root")
    descent.add_argument("modulus", type=int)
    descent.add_argument("root", type=int)

    bridges = sub.add_parser("verify-root-bridges")
    bridges.add_argument("--max-modulus", type=int, default=5000)

    normal = sub.add_parser("verify-descent-normal-form")
    normal.add_argument("--max-modulus", type=int, default=20000)

    pair = sub.add_parser("compare-roots")
    pair.add_argument("modulus", type=int)
    pair.add_argument("root1", type=int)
    pair.add_argument("root2", type=int)

    fake = sub.add_parser("scan-markov-fakes")
    fake.add_argument("--max-label", type=int, default=10**12)

    args = parser.parse_args()
    if args.command == "verify-orientation":
        verify_orientation(args.depth)
    elif args.command == "search-collisions":
        search_collisions(10 ** args.digits)
    elif args.command == "recognize-root":
        recognize_root(args.modulus, args.root)
    elif args.command == "scan-palindromes":
        scan_palindromes(args.inner)
    elif args.command == "descent-root":
        result = arithmetic_cohn_descent(args.modulus, args.root)
        print(result)
    elif args.command == "verify-root-bridges":
        verify_root_bridges(args.max_modulus)
    elif args.command == "verify-descent-normal-form":
        verify_arithmetic_descent_normal_form(args.max_modulus)
    elif args.command == "compare-roots":
        compare_root_pair(args.modulus, args.root1, args.root2)
    elif args.command == "scan-markov-fakes":
        scan_markov_fake_roots(args.max_label)


if __name__ == "__main__":
    main()
