#!/usr/bin/env python3
"""Research-only Markov/Farey experiments for LeanFrontier.

This file is deliberately not a Lean submission. It mirrors the accepted
OrientedNode/child recursion closely enough to test proposed bridges before
formalization.

Experiments:
1. verify-orientation: verify a six-state transducer carrying the planar
   Farey/Markov left-centre-right frame into LeanFrontier's coordinate-labelled
   oriented tree.
2. search-collisions: enumerate the planar Markov tree below a numerical bound
   and look for duplicate maximal Markov labels attached to distinct unordered
   triples.
3. recognize-root: construct Zhang's matrix from a modular root and test
   membership in the positive Cohn monoid generated by A and B.
4. scan-palindromes: enumerate matrices M_(a p b) with p palindromic, record
   collisions of their candidate denominators, and distinguish central
   palindromes (the Christoffel/Markov subclass) from arbitrary palindromes.

The searches are exploratory sanity checks. Finite negative searches are not
evidence for the open uniqueness conjecture.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from enum import IntEnum
from itertools import product


class Move(IntEnum):
    FIRST = 0
    SECOND = 1
    THIRD = 2


State = tuple[int, int, int]


@dataclass(frozen=True)
class Oriented:
    state: State
    back: Move


def jump(b: int, c: int, a: int) -> int:
    return 3 * b * c - a


def move(which: Move, state: State) -> State:
    x, y, z = state
    if which == Move.FIRST:
        return (jump(y, z, x), y, z)
    if which == Move.SECOND:
        return (x, jump(x, z, y), z)
    return (x, y, jump(x, y, z))


def forward_move(back: Move, direction: bool) -> Move:
    table = {
        Move.FIRST: (Move.SECOND, Move.THIRD),
        Move.SECOND: (Move.FIRST, Move.THIRD),
        Move.THIRD: (Move.FIRST, Move.SECOND),
    }
    return table[back][1 if direction else 0]


def child(node: Oriented, direction: bool) -> Oriented:
    changed = forward_move(node.back, direction)
    return Oriented(move(changed, node.state), changed)


ORIENTED_ROOT = Oriented((1, 1, 2), Move.THIRD)


def follow(bits: tuple[bool, ...]) -> Oriented:
    node = ORIENTED_ROOT
    for bit in bits:
        node = child(node, bit)
    return node


# A frame stores which physical coordinate currently means
# (left Farey boundary, centre/Markov number, right Farey boundary).
Frame = tuple[Move, Move, Move]

# At (1, 2, 1), put the left boundary in coordinate SECOND, the centre in
# coordinate THIRD, and the right boundary in coordinate FIRST. With this
# convention the first classical L/R step maps to Lean false/true.
ROOT_FRAME: Frame = (Move.SECOND, Move.THIRD, Move.FIRST)


def direction_for_changed_coordinate(back: Move, target: Move) -> bool:
    for direction in (False, True):
        if forward_move(back, direction) == target:
            return direction
    raise AssertionError("target must be one of the two non-back coordinates")


def frame_step(frame: Frame, planar_direction: str) -> tuple[bool, Frame]:
    left, centre, right = frame
    if planar_direction == "L":
        out = direction_for_changed_coordinate(centre, right)
        return out, (left, right, centre)
    if planar_direction == "R":
        out = direction_for_changed_coordinate(centre, left)
        return out, (centre, left, right)
    raise ValueError("planar path must contain only L/R")


def translate_planar_path(path: str) -> tuple[tuple[bool, ...], Frame]:
    frame = ROOT_FRAME
    bits: list[bool] = []
    for step in path:
        out, frame = frame_step(frame, step)
        bits.append(out)
    return tuple(bits), frame


@dataclass(frozen=True)
class PlanarNode:
    """Planar Farey/Markov frame (left label, centre label, right label)."""

    left: int
    centre: int
    right: int


PLANAR_ROOT = PlanarNode(1, 2, 1)


def planar_child(node: PlanarNode, direction: str) -> PlanarNode:
    l, m, r = node.left, node.centre, node.right
    if direction == "L":
        return PlanarNode(l, 3 * l * m - r, m)
    if direction == "R":
        return PlanarNode(m, 3 * m * r - l, r)
    raise ValueError("planar path must contain only L/R")


def planar_follow(path: str) -> PlanarNode:
    node = PLANAR_ROOT
    for step in path:
        node = planar_child(node, step)
    return node


def expected_lean_state(planar: PlanarNode, frame: Frame) -> State:
    values = {
        frame[0]: planar.left,
        frame[1]: planar.centre,
        frame[2]: planar.right,
    }
    return (values[Move.FIRST], values[Move.SECOND], values[Move.THIRD])


def all_paths(max_depth: int):
    yield ""
    for depth in range(1, max_depth + 1):
        for letters in product("LR", repeat=depth):
            yield "".join(letters)


def verify_orientation(max_depth: int) -> None:
    checked = 0
    for path in all_paths(max_depth):
        bits, frame = translate_planar_path(path)
        lean = follow(bits)
        planar = planar_follow(path)
        expected = expected_lean_state(planar, frame)
        if lean.state != expected or lean.back != frame[1]:
            raise AssertionError(
                f"orientation mismatch at {path!r}: "
                f"lean={lean}, planar={planar}, frame={frame}, expected={expected}"
            )
        checked += 1

    print(f"verified {checked} planar nodes through depth {max_depth}")
    print("six-state transition table (frame=L/M/R coordinate numbers):")
    reachable = set()
    frontier = [ROOT_FRAME]
    while frontier:
        frame = frontier.pop()
        if frame in reachable:
            continue
        reachable.add(frame)
        for step in "LR":
            _, nxt = frame_step(frame, step)
            frontier.append(nxt)

    def frame_name(frame: Frame) -> str:
        return "".join(str(int(x) + 1) for x in frame)

    for frame in sorted(reachable, key=lambda f: tuple(map(int, f))):
        pieces = []
        for step in "LR":
            bit, nxt = frame_step(frame, step)
            pieces.append(f"{step}->{int(bit)}:{frame_name(nxt)}")
        print(f"  {frame_name(frame)}  " + "  ".join(pieces))

    print("sample planar path -> direct Lean child bits -> sternNode path")
    for path in ("L", "R", "LL", "LR", "RL", "RR", "LLL", "LLR"):
        bits, _ = translate_planar_path(path)
        direct = "".join("R" if b else "L" for b in bits)
        stern = direct[::-1]  # sternNode follows path.reverse
        print(f"  {path:3} -> {direct:3} -> {stern:3}")


def search_collisions(max_label: int) -> None:
    stack: list[tuple[str, PlanarNode]] = [("", PLANAR_ROOT)]
    by_label: dict[int, tuple[str, tuple[int, int, int]]] = {}
    collisions: list[
        tuple[int, tuple[str, tuple[int, int, int]], tuple[str, tuple[int, int, int]]]
    ] = []
    visited = 0
    deepest = 0

    while stack:
        path, node = stack.pop()
        if node.centre > max_label:
            continue
        visited += 1
        deepest = max(deepest, len(path))
        triple = tuple(sorted((node.left, node.centre, node.right)))
        old = by_label.get(node.centre)
        if old is not None and old[1] != triple:
            collisions.append((node.centre, old, (path, triple)))
        else:
            by_label[node.centre] = (path, triple)

        left = planar_child(node, "L")
        right = planar_child(node, "R")
        if left.centre <= max_label:
            stack.append((path + "L", left))
        if right.centre <= max_label:
            stack.append((path + "R", right))

    print(
        f"visited={visited} max_label={max_label} deepest_path={deepest} "
        f"distinct_labels={len(by_label)} collisions={len(collisions)}"
    )
    for item in collisions[:20]:
        print("collision:", item)




# Cohn generators used in the word model of Markov numbers.
# See Lagisquet--Pelantová--Tavenas--Vuillon (2021).
Matrix = tuple[tuple[int, int], tuple[int, int]]
A: Matrix = ((1, 1), (1, 2))
B: Matrix = ((2, 1), (1, 1))
A_INV: Matrix = ((2, -1), (-1, 1))
B_INV: Matrix = ((1, -1), (-1, 2))
IDENTITY: Matrix = ((1, 0), (0, 1))


def matrix_mul(x: Matrix, y: Matrix) -> Matrix:
    return (
        (
            x[0][0] * y[0][0] + x[0][1] * y[1][0],
            x[0][0] * y[0][1] + x[0][1] * y[1][1],
        ),
        (
            x[1][0] * y[0][0] + x[1][1] * y[1][0],
            x[1][0] * y[0][1] + x[1][1] * y[1][1],
        ),
    )


def matrix_transpose(x: Matrix) -> Matrix:
    return ((x[0][0], x[1][0]), (x[0][1], x[1][1]))


def word_matrix(word: str) -> Matrix:
    out = IDENTITY
    for letter in word:
        if letter == "a":
            out = matrix_mul(out, A)
        elif letter == "b":
            out = matrix_mul(out, B)
        else:
            raise ValueError("Cohn words contain only a/b")
    return out


def root_core_matrix(modulus: int, root: int) -> Matrix:
    """Symmetric determinant-one core attached to a modular root.

    Put v=(u^2+1)/M. Then
      P(M,u) = [[M-2u+v, u-v], [u-v, v]]
    has determinant one, and A * P(M,u) * B is exactly the transposed
    Zhang candidate matrix used below.
    """
    if modulus <= 0:
        raise ValueError("modulus must be positive")
    root %= modulus
    if (root * root + 1) % modulus:
        raise ValueError("root must satisfy root^2 == -1 mod modulus")
    v = (root * root + 1) // modulus
    core = (
        (modulus - 2 * root + v, root - v),
        (root - v, v),
    )
    if core[0][0] * core[1][1] - core[0][1] * core[1][0] != 1:
        raise AssertionError("root core must have determinant one")
    return core


def zhang_candidate_matrix(modulus: int, root: int) -> Matrix:
    """Transpose of Zhang's Proposition-8 matrix, in our A/B convention."""
    core = root_core_matrix(modulus, root)
    candidate = matrix_mul(matrix_mul(A, core), B)

    root %= modulus
    v = (root * root + 1) // modulus
    expected = (
        (2 * modulus - root, modulus),
        (2 * modulus + root - v, modulus + root),
    )
    if candidate != expected:
        raise AssertionError("A * root_core * B must equal Zhang candidate")
    return candidate


def matrix_nonnegative(x: Matrix) -> bool:
    return all(entry >= 0 for row in x for entry in row)


def recognize_cohn_word(x: Matrix) -> str | None:
    """Recognize x in the free positive monoid generated by A and B.

    We strip a possible last generator by right multiplication by A^-1/B^-1.
    The DFS is tiny for the matrices considered here and also doubles as a
    check that no greedy convention has been smuggled into the experiment.
    """
    stack: list[tuple[Matrix, str]] = [(x, "")]
    seen: set[Matrix] = set()
    while stack:
        current, reversed_word = stack.pop()
        if current == IDENTITY:
            return reversed_word[::-1]
        if current in seen:
            continue
        seen.add(current)
        for letter, inverse in (("a", A_INV), ("b", B_INV)):
            parent = matrix_mul(current, inverse)
            if matrix_nonnegative(parent):
                stack.append((parent, reversed_word + letter))
    return None


def centered_index_from_word_matrix(x: Matrix) -> tuple[int, int]:
    """Return (candidate denominator, root modulo sign) for a special word."""
    modulus = x[0][1]
    if modulus <= 0:
        raise ValueError("expected positive upper-right entry")
    root = (x[1][1] - modulus) % modulus
    return modulus, min(root, modulus - root)


def is_period(word: str, period: int) -> bool:
    if period <= 0:
        return False
    if period >= len(word):
        return True
    return all(word[i] == word[i + period] for i in range(len(word) - period))


def is_central_palindrome(word: str) -> bool:
    """Classical central-word criterion: coprime periods p,q, |w|=p+q-2."""
    from math import gcd

    if word != word[::-1]:
        return False
    n = len(word)
    for p in range(1, n + 2):
        q = n + 2 - p
        if gcd(p, q) == 1 and is_period(word, p) and is_period(word, q):
            return True
    return False


def palindromes(length: int):
    half = (length + 1) // 2
    for bits in product("ab", repeat=half):
        first = "".join(bits)
        if length % 2 == 0:
            yield first + first[::-1]
        else:
            yield first + first[-2::-1]


def continued_fraction(numerator: int, denominator: int) -> list[int]:
    """Regular continued fraction of a positive rational numerator/denominator."""
    if numerator <= 0 or denominator <= 0:
        raise ValueError("continued fractions here expect positive arguments")
    out: list[int] = []
    while denominator:
        quotient, remainder = divmod(numerator, denominator)
        out.append(quotient)
        numerator, denominator = denominator, remainder
    return out


def recognize_root(modulus: int, root: int) -> None:
    centered = min(root % modulus, (-root) % modulus)
    cf = continued_fraction(modulus, centered)
    first_bad = next((i for i, digit in enumerate(cf) if digit not in (1, 2)), None)
    print(f"M={modulus} centered_root={centered}")
    print(
        f"  M/u continued fraction={cf} all_1_or_2={first_bad is None} "
        f"first_non_12_index={first_bad}"
    )
    for representative in sorted({centered, (-centered) % modulus}):
        if (representative * representative + 1) % modulus:
            print(f"  {representative}: not a square root of -1")
            continue
        core = root_core_matrix(modulus, representative)
        candidate = zhang_candidate_matrix(modulus, representative)
        core_word = recognize_cohn_word(core)
        word = recognize_cohn_word(candidate)
        if word is None:
            print(
                f"  {representative}: candidate does not lie in <A,B>; "
                f"core={core} core_word={core_word}"
            )
            continue
        inner = word[1:-1] if len(word) >= 2 and word[0] == "a" and word[-1] == "b" else None
        central = inner is not None and is_central_palindrome(inner)
        print(
            f"  {representative}: core={core} core_word={core_word} "
            f"word={word} palindrome_inner="
            f"{inner is not None and inner == inner[::-1]} central={central}"
        )


def scan_palindromes(max_inner_length: int) -> None:
    """Search the wider a-palindrome-b class for denominator/root collisions."""
    # denominator -> centered root -> (one witness, central?, unordered endpoint counts)
    groups: dict[int, dict[int, tuple[str, bool, tuple[int, int]]]] = {}
    # A second index deliberately ignores the root and asks the stronger question:
    # can one m-value occur for two different unordered endpoint-count pairs?
    endpoint_groups: dict[int, dict[tuple[int, int], str]] = {}
    total_words = 0
    central_words = 0

    for inner_length in range(max_inner_length + 1):
        for inner in palindromes(inner_length):
            word = "a" + inner + "b"
            matrix = word_matrix(word)
            modulus, root = centered_index_from_word_matrix(matrix)

            # For a palindrome this identity follows symbolically from
            # A [[x,y],[y,z]] B; keep it as an executable guard.
            trace = matrix[0][0] + matrix[1][1]
            if trace != 3 * modulus:
                raise AssertionError(f"palindrome identity failed for {word}")

            central = is_central_palindrome(inner)
            counts = tuple(sorted((word.count("a"), word.count("b"))))
            total_words += 1
            central_words += int(central)
            roots = groups.setdefault(modulus, {})
            old = roots.get(root)
            if old is None or (central and not old[1]):
                roots[root] = (word, central, counts)
            endpoint_groups.setdefault(modulus, {}).setdefault(counts, word)

    broad_collisions = [
        (modulus, roots) for modulus, roots in groups.items() if len(roots) > 1
    ]
    mixed_collisions = [
        (modulus, roots)
        for modulus, roots in broad_collisions
        if any(central for _, central, _ in roots.values())
    ]
    cross_endpoint_collisions = [
        (modulus, endpoints)
        for modulus, endpoints in endpoint_groups.items()
        if len(endpoints) > 1
    ]

    print(
        f"inner<= {max_inner_length}: words={total_words} "
        f"candidate_denominators={len(groups)} central_words={central_words} "
        f"multi_root_denominators={len(broad_collisions)} "
        f"central_involved_multi_root={len(mixed_collisions)} "
        f"cross_endpoint_denominators={len(cross_endpoint_collisions)}"
    )

    print("first broad collisions:")
    for modulus, roots in sorted(broad_collisions)[:10]:
        summary = ", ".join(
            f"root={root} word={word} central={central} counts={counts}"
            for root, (word, central, counts) in sorted(roots.items())
        )
        print(f"  M={modulus}: {summary}")

    if mixed_collisions:
        print("WARNING: central-involved collisions found")
        for modulus, roots in sorted(mixed_collisions)[:20]:
            print(f"  M={modulus}: {roots}")
    else:
        print("no central-involved collision in this finite scan")

    if cross_endpoint_collisions:
        print("WARNING: equal m-values across distinct endpoint-count pairs found")
        for modulus, endpoints in sorted(cross_endpoint_collisions)[:20]:
            print(f"  M={modulus}: {endpoints}")
    else:
        print("no equal m-value across distinct unordered endpoint counts in this finite scan")


def main() -> None:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)

    verify = sub.add_parser("verify-orientation")
    verify.add_argument("--depth", type=int, default=12)

    search = sub.add_parser("search-collisions")
    search.add_argument(
        "--digits",
        type=int,
        default=100,
        help="search nodes with centre Markov label <= 10**digits",
    )

    root = sub.add_parser("recognize-root")
    root.add_argument("modulus", type=int)
    root.add_argument("root", type=int)

    pal = sub.add_parser("scan-palindromes")
    pal.add_argument("--inner", type=int, default=30)

    args = parser.parse_args()
    if args.command == "verify-orientation":
        verify_orientation(args.depth)
    elif args.command == "search-collisions":
        search_collisions(10 ** args.digits)
    elif args.command == "recognize-root":
        recognize_root(args.modulus, args.root)
    elif args.command == "scan-palindromes":
        scan_palindromes(args.inner)


if __name__ == "__main__":
    main()
